# Generated by Django 4.2.17 on 2025-01-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_collaboraterequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CollaborateRequest',
            new_name='ContactRequest',
        ),
    ]
