# Generated by Django 4.2.17 on 2025-01-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
